export const TRENDING = 'TRENDING'
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const GET_OFFER_PRODUCTS = "GET_OFFER_PRODUCTS";
export const GET_FEATURED_CATEGORIES = "GET_FEATURED_CATEGORIES";
